In [15]:
from sklearn.datasets import load_diabetes
import pandas as pd
import numpy as np
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score
from sklearn.model_selection import train_test_split

In [16]:
df= pd.DataFrame({'cgpa':[1,3,4,6,7],'iq':[10,14,15,18,20],'package':[9,10,13,14,16]})
df

cgpa  iq  package
0     1  10        9
1     3  14       10
2     4  15       13
3     6  18       14
4     7  20       16

In [18]:
X = df.iloc[:,0:2]
y = df.iloc[:,-1]

In [19]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=2)

In [39]:
X_train

cgpa  iq
4     7  20
1     3  14
3     6  18
0     1  10

In [20]:
reg = LinearRegression()
reg.fit(X_train,y_train)

LinearRegression()

In [21]:
reg.coef_

array([ 2.7 , -0.95])

In [22]:
reg.intercept_

15.50000000000004

In [24]:
y_hat = np.dot(X_train,reg.coef_) + reg.intercept_
y_hat

array([15.4, 10.3, 14.6,  8.7])

In [25]:
intercept_der = -2 * np.mean(y_train - y_hat)

In [26]:
intercept_der

2.6645352591003757e-15

In [28]:
lr = 0.1

In [30]:
reg.intercept_ = reg.intercept_ - (lr * intercept_der)
reg.intercept_

15.50000000000004

In [40]:
X_train.shape[0]

4

In [34]:
 coef_der = -2 * np.dot((y_train - y_hat),X_train)/X_train.shape[0]
   

In [33]:
 coef_der 

array([2.66453526e-15, 2.66453526e-14])

In [36]:
reg.coef_ = reg.coef_ - (lr * coef_der)
reg.coef_ 

array([ 2.7 , -0.95])

In [41]:
X_test

cgpa  iq
2     4  15

In [37]:
y_hat = np.dot(X_test,reg.coef_) + reg.intercept_
y_hat

array([12.05])

In [42]:
y_test

2    13
Name: package, dtype: int64

In [38]:
r2_score(y_test,y_hat)

C:\Users\Faizan computer\anaconda3\Lib\site-packages\sklearn\metrics\_regression.py:996: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)


nan

# Example 02

In [2]:
X,y = load_diabetes(return_X_y=True)


In [4]:
X

array([[ 0.03807591,  0.05068012,  0.06169621, ..., -0.00259226,
         0.01990749, -0.01764613],
       [-0.00188202, -0.04464164, -0.05147406, ..., -0.03949338,
        -0.06833155, -0.09220405],
       [ 0.08529891,  0.05068012,  0.04445121, ..., -0.00259226,
         0.00286131, -0.02593034],
       ...,
       [ 0.04170844,  0.05068012, -0.01590626, ..., -0.01107952,
        -0.04688253,  0.01549073],
       [-0.04547248, -0.04464164,  0.03906215, ...,  0.02655962,
         0.04452873, -0.02593034],
       [-0.04547248, -0.04464164, -0.0730303 , ..., -0.03949338,
        -0.00422151,  0.00306441]])

In [5]:
y

array([151.,  75., 141., 206., 135.,  97., 138.,  63., 110., 310., 101.,
        69., 179., 185., 118., 171., 166., 144.,  97., 168.,  68.,  49.,
        68., 245., 184., 202., 137.,  85., 131., 283., 129.,  59., 341.,
        87.,  65., 102., 265., 276., 252.,  90., 100.,  55.,  61.,  92.,
       259.,  53., 190., 142.,  75., 142., 155., 225.,  59., 104., 182.,
       128.,  52.,  37., 170., 170.,  61., 144.,  52., 128.,  71., 163.,
       150.,  97., 160., 178.,  48., 270., 202., 111.,  85.,  42., 170.,
       200., 252., 113., 143.,  51.,  52., 210.,  65., 141.,  55., 134.,
        42., 111.,  98., 164.,  48.,  96.,  90., 162., 150., 279.,  92.,
        83., 128., 102., 302., 198.,  95.,  53., 134., 144., 232.,  81.,
       104.,  59., 246., 297., 258., 229., 275., 281., 179., 200., 200.,
       173., 180.,  84., 121., 161.,  99., 109., 115., 268., 274., 158.,
       107.,  83., 103., 272.,  85., 280., 336., 281., 118., 317., 235.,
        60., 174., 259., 178., 128.,  96., 126., 28

In [6]:
print(X.shape)
print(y.shape)

(442, 10)
(442,)


In [7]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=2)

In [8]:
reg = LinearRegression()
reg.fit(X_train,y_train)

LinearRegression()

In [10]:
reg.coef_

array([  -9.15865318, -205.45432163,  516.69374454,  340.61999905,
       -895.5520019 ,  561.22067904,  153.89310954,  126.73139688,
        861.12700152,   52.42112238])

In [11]:

reg.intercept_

151.88331005254167

In [12]:
y_pred = reg.predict(X_test)
r2_score(y_test,y_pred)

0.4399338661568969

In [13]:
X_train.shape

(353, 10)

In [96]:
class GDRegressor:
    
    def __init__(self,learning_rate=0.01,epochs=100):
        
        self.coef_ = None
        self.intercept_ = None
        self.lr = learning_rate
        self.epochs = epochs
        
    def fit(self,X_train,y_train):
        # init your coefs
        self.intercept_ = 0
        self.coef_ = np.ones(X_train.shape[1])
        
        for i in range(self.epochs):
            # update all the coef and the intercept
            y_hat = np.dot(X_train,self.coef_) + self.intercept_
            #print("Shape of y_hat",y_hat.shape)
            intercept_der = -2 * np.mean(y_train - y_hat)
            self.intercept_ = self.intercept_ - (self.lr * intercept_der)
            
            coef_der = -2 * np.dot((y_train - y_hat),X_train)/X_train.shape[0]
            self.coef_ = self.coef_ - (self.lr * coef_der)
        
        print(self.intercept_,self.coef_)
    
    def predict(self,X_test):
        return np.dot(X_test,self.coef_) + self.intercept_

In [109]:
gdr = GDRegressor(epochs=1000,learning_rate=0.5)

In [110]:
gdr.fit(X_train,y_train)

152.0135263267291 [  14.38915082 -173.72674118  491.54504015  323.91983579  -39.32680194
 -116.01099114 -194.04229501  103.38216641  451.63385893   97.57119174]


In [111]:
y_pred = gdr.predict(X_test)

In [112]:
r2_score(y_test,y_pred)

0.4534524671450598