In [1]:
import numpy as np 
import pandas as pd 
import seaborn as sns 
import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv("ML Algorithms/Social_Network_Ads (2).csv")

In [3]:
df.head()

Age  EstimatedSalary  Purchased
0   19            19000          0
1   35            20000          0
2   26            43000          0
3   27            57000          0
4   19            76000          0

In [4]:
df["Purchased"].value_counts()

0    257
1    143
Name: Purchased, dtype: int64

In [5]:
x = df.iloc[ : ,:-1]
y = df["Purchased"]

In [6]:
from sklearn.model_selection import train_test_split

In [7]:
x_train , x_test , y_train , y_test = train_test_split(x  , y , test_size=0.2 , random_state=42)

In [8]:
from sklearn.linear_model import LogisticRegression

In [9]:
lr = LogisticRegression()

In [10]:
lr.fit(x_train , y_train)

LogisticRegression()

In [11]:
lr.score(x_test, y_test )

0.65

In [12]:
lr.predict([[19 , 19000]])

C:\ProgramData\anaconda3\Lib\site-packages\sklearn\base.py:464: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(


array([0], dtype=int64)

In [13]:
lr.predict([[46 , 28000]])

C:\ProgramData\anaconda3\Lib\site-packages\sklearn\base.py:464: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(


array([0], dtype=int64)

# imblearn

In [ ]:
pip install imblearn

In [14]:
df["Purchased"].value_counts()

0    257
1    143
Name: Purchased, dtype: int64

In [15]:
x = df.iloc[ : ,:-1]
y = df["Purchased"]

In [16]:
import sklearn

print(f"scikit-learn version: {sklearn.__version__}")


scikit-learn version: 1.3.0


In [17]:
import imblearn
print(f"imbalanced-learn version: {imblearn.__version__}")

imbalanced-learn version: 0.9.1


In [22]:
pip install imblearn

Defaulting to user installation because normal site-packages is not writeableNote: you may need to restart the kernel to use updated packages.



In [21]:
pip install imbalanced-learn

Defaulting to user installation because normal site-packages is not writeable
Note: you may need to restart the kernel to use updated packages.


In [18]:
from imblearn.over_sampling import RandomOverSampler

In [19]:
from imblearn.under_sampling import RandomUnderSampler

In [20]:
ru = RandomUnderSampler()

In [21]:
ru_x , ru_y  = ru.fit_resample(x , y )

In [22]:
ru_y.value_counts()

0    143
1    143
Name: Purchased, dtype: int64

In [29]:
y.shape

(400,)

In [30]:
ru_y.shape

(286,)

In [23]:
x_train , x_test , y_train , y_test = train_test_split(ru_x  , ru_y , test_size=0.2 , random_state=42)

In [24]:
from sklearn.linear_model import LogisticRegression

In [25]:
lr = LogisticRegression()

In [26]:
lr.fit(x_train , y_train)

LogisticRegression()

In [27]:
lr.score(x_test, y_test )

0.5862068965517241

In [28]:
lr.predict([[19 , 19000]])

C:\ProgramData\anaconda3\Lib\site-packages\sklearn\base.py:464: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(


array([1], dtype=int64)