# Support Vector Regression (SVR)
is a type of Support Vector Machine (SVM) used for regression tasks. SVR aims to find a function that deviates from the target values by a value no greater than a specified margin 
𝜖
ϵ and is as flat as possible.

In [1]:
import numpy as np 
import pandas as pd 
import seaborn as sns 
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split 
from sklearn.preprocessing import StandardScaler


In [2]:
data = pd.read_csv(r"C:\Users\Mega Computers\Desktop\Datasets\bangalore house price prediction OHE-data.csv")

In [3]:
data.head()

bath  balcony  price  total_sqft_int  bhk  price_per_sqft  \
0   3.0      2.0  150.0          1672.0    3     8971.291866   
1   3.0      3.0  149.0          1750.0    3     8514.285714   
2   3.0      2.0  150.0          1750.0    3     8571.428571   
3   2.0      2.0   40.0          1250.0    2     3200.000000   
4   2.0      2.0   83.0          1200.0    2     6916.666667   

   area_typeSuper built-up  Area  area_typeBuilt-up  Area  \
0                              1                        0   
1                              0                        1   
2                              1                        0   
3                              1                        0   
4                              0                        0   

   area_typePlot  Area  availability_Ready To Move  ...  \
0                    0                           1  ...   
1                    0                           1  ...   
2                    0                           1  ...   
3                    0                           1  ...   
4                    1                           1  ...   

   location_Kalena Agrahara  location_Horamavu Agara  location_Vidyaranyapura  \
0                         0                        0                        0   
1                         0                        0                        0   
2                         0                        0                        0   
3                         0                        0                        0   
4                         0                        0                        0   

   location_BTM 2nd Stage  location_Hebbal Kempapura  location_Hosur Road  \
0                       0                          0                    0   
1                       0                          0                    0   
2                       0                          0                    0   
3                       0                          0                    0   
4                       0                          0                    0   

   location_Horamavu Banaswadi  location_Domlur  location_Mahadevpura  \
0                            0                0                     0   
1                            0                0                     0   
2                            0                0                     0   
3                            0                0                     0   
4                            0                0                     0   

   location_Tumkur Road  
0                     0  
1                     0  
2                     0  
3                     0  
4                     0  

[5 rows x 108 columns]

In [4]:
data.shape

(7120, 108)

In [5]:
y = data["price"]
X = data.drop("price" , axis=1)
print("shapae of x = " , X.shape)
print("shapae of y= " , y.shape)

shapae of x =  (7120, 107)
shapae of y=  (7120,)


In [6]:
x_train , x_test , y_train , y_test = train_test_split(X , y , test_size=0.2 , random_state=42)

In [7]:
sc =StandardScaler()
sc.fit(x_train)
X_train = sc.transform(x_train)
X_test = sc.transform(x_test)
X_train

array([[-0.44422611,  0.54630035,  0.07232582, ..., -0.04782807,
        -0.05138463, -0.04782807],
       [ 0.6879045 ,  1.83462341,  0.17729421, ..., -0.04782807,
        -0.05138463, -0.04782807],
       [-0.44422611, -0.74202271, -0.50500027, ..., -0.04782807,
        -0.05138463, -0.04782807],
       ...,
       [-0.44422611,  0.54630035, -0.35279612, ..., -0.04782807,
        -0.05138463, -0.04782807],
       [ 0.6879045 ,  0.54630035,  0.98030232, ..., -0.04782807,
        -0.05138463, -0.04782807],
       [-0.44422611,  0.54630035, -0.12186568, ..., -0.04782807,
        -0.05138463, -0.04782807]])

In [8]:
from sklearn.svm import SVR

In [9]:
svrp = SVR(kernel='poly' , degree=3)
svrp.fit(x_train , y_train)
svrp.score(x_test , y_test)

0.7010777318712575

In [10]:
svrp.fit(x_train , y_train)


SVR(kernel='poly')

In [11]:
svrp.score( x_test ,y_test )*100

70.10777318712576

In [14]:
y_pre_P = svrp.predict(x_test)
y_pre_svr =svr_rbf.predict(x_test)
# y_pre_lr=svr_lr.predict(x_test)

In [15]:

svrp.predict([X_test[0]])


C:\ProgramData\anaconda3\Lib\site-packages\sklearn\base.py:464: UserWarning: X does not have valid feature names, but SVR was fitted with feature names
  warnings.warn(


array([38.00144976])

In [16]:
svr_rbf.predict([X_test[0]])

C:\ProgramData\anaconda3\Lib\site-packages\sklearn\base.py:464: UserWarning: X does not have valid feature names, but SVR was fitted with feature names
  warnings.warn(


array([27.09279033])

In [ ]:
svr_lr = SVR(kernel='linear')
svr_lr.fit(x_train , y_train)
svr_lr.score(x_test , y_test)

In [13]:
svr_rbf = SVR(kernel='rbf')
svr_rbf.fit(x_train , y_train)
svr_rbf.score(x_test , y_test)*100

56.40557145169895

In [17]:
X_test[0]

array([-0.44422611,  0.54630035, -0.34334897, -0.55044507, -0.72383255,
        0.57680968, -0.47233992, -0.25703648,  0.50597314, -0.18727461,
       -0.16162122, -0.15580825, -0.1288342 , -0.13023539, -0.12812824,
       -0.12234347,  7.59747652, -0.12741862, -0.12234347, -0.10909925,
       -0.1082724 , -0.1082724 , -0.11472827, -0.10743948, -0.09218776,
       -0.09315135, -0.08823182, -0.08923672, -0.09023078, -0.08195215,
       -0.08514823, -0.0830308 , -0.08514823, -0.07276497, -0.07975227,
       -0.07975227, -0.07749158, -0.0739743 , -0.06901264, -0.0751646 ,
       -0.07153563, -0.0751646 , -0.0751646 , -0.0751646 , -0.07749158,
       -0.07633675, -0.07276497, -0.06901264, -0.0739743 , -0.07276497,
       -0.07028523, -0.06504853, -0.0677166 , -0.0677166 , -0.0677166 ,
       -0.06504853, -0.07153563, -0.06367332, -0.06226825, -0.06639573,
       -0.06226825, -0.06367332, -0.06504853, -0.06504853, -0.06504853,
       -0.06083125, -0.05785186, -0.06639573, -0.06226825, -0.06

In [19]:
from sklearn.metrics import mean_absolute_error
import numpy as np

mse = mean_absolute_error(y_test , y_pre_P)
rmse = np.sqrt(mse)

In [20]:
rmse

3.926702506326713

In [21]:
mse

15.41899257319249